boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.37.tar.gz:
  size: 2299767
  object_id: 8430a2b5-c852-413d-4286-3d1a44e8e61d
  sha: sha256:04e214c0c40a97b8a5c2b4ae88a3aa8a93e6f2e45c6b3534ddac351f26548577
mariadb/mariadb-10.6.4.tar.gz:
  size: 84947143
  object_id: dbe92cb6-b7ec-470c-4010-3bdf5fde2c01
  sha: sha256:75bf9b147a95d38160d01a73b098d50a1960563b46d16a235971fff64d99643c
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.34.tar.gz:
  size: 56150251
  object_id: 3af57f7a-0978-42d9-6693-13f7a500b5ce
  sha: sha256:78d2aeb1320226590755a5734383c2f61284c337dad7f947bdff345f790686a6
postgres/postgresql-9.6.23.tar.gz:
  size: 24705627
  object_id: eac3e8b7-8cc0-4fdb-5c05-4c1972e12e68
  sha: sha256:679a7004871d3af4fd70144a6f885db00a8337bd384504527e7b579e81f35926
postgres/postgresql-10.18.tar.gz:
  size: 25147889
  object_id: c475eeae-f966-4964-47e1-092155a13f65
  sha: sha256:c7f2ebede55c855999d4586b3a79c4b2609140df6b4e1e444cd41bee3f80977d
postgres/postgresql-11.13.tar.gz:
  size: 26333483
  object_id: 5a69ea14-47fe-4efb-66e4-46e8d42d2f7e
  sha: sha256:89caabd42c0069d4fabe75e13f06e702754dcb1527c2ef9f728e2cb74584e03f
postgres/postgresql-13.4.tar.gz:
  size: 27687091
  object_id: 4aba70e5-7508-409e-7a9d-e151068e7dd4
  sha: sha256:59d7bc523e78570c549876fed297ec3e46dd307e90f5b1d22f49181191cf203e
