boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.47.tar.gz:
  size: 2792969
  object_id: 9bd5dd3e-b4a0-4733-447a-ba56776d23d8
  sha: sha256:c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16
mariadb/mariadb-10.6.25.tar.gz:
  size: 108006288
  object_id: 7f22caed-d110-494c-68bc-85ba6e8ce684
  sha: sha256:ae221fbcaf3730070343e848e11e256092ba52c6fcf51a510374931720240a6c
mysql/mysql-5.7.44.tar.gz:
  size: 56570597
  object_id: 92e82aaa-6a33-40b7-5940-2366d90ad636
  sha: sha256:d03d8ff688862c40da3488451072a4b2178a86b53b4a7546ee5f864bb15cd919
mysql/mysql-8.0.45-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 61251552
  object_id: 3a87799f-20e0-4ee7-7750-dda370823ae5
  sha: sha256:a524f4163e7807b3e07cfe0109a13379bb8da4d3bdfac8521ae7f1ecb1623ab5
ncurses/ncurses-6.6.tar.gz:
  size: 3791150
  object_id: 66926dd4-d034-4092-41d2-506b35dd7eba
  sha: sha256:355b4cbbed880b0381a04c46617b7656e362585d52e9cf84a67e2009b749ff11
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: 9abf36c3-f575-40b8-6891-2f7c415b6b6b
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.17.tar.gz:
  size: 30677569
  object_id: b2685a33-15fb-4c6c-4a86-65f47a35b106
  sha: sha256:f7fc926ea77ffc52e9d6fd58276427e3fe14d35fd9ff3ccf724ca88a28bcb4df
