boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.40.tar.gz:
  size: 2359622
  object_id: 71c9fce6-53f5-4775-525c-fb5a75a3528a
  sha: sha256:ded42661cab30ada2e72ebff9e725e745b4b16ce831993635136f2ef86177724
mariadb/mariadb-10.6.7.tar.gz:
  size: 85882896
  object_id: 95ea4190-f866-4027-7248-0ecd859ef15c
  sha: sha256:75ee0f1f865a765fc461ab165419417a719e308faba784b2c97ecbe9e4b4b2c5
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.37.tar.gz:
  size: 56248775
  object_id: bda6d410-4f86-42b3-600a-7705c210ee57
  sha: sha256:a99a9aa8635d2566dab764b2de56bed1730365d360e20bb27f56392ce54e18bd
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.20.tar.gz:
  size: 25307690
  object_id: d017c385-856a-4865-7cf9-1e93bced4fc4
  sha: sha256:403bdad47101f7c0a15824627dd0fa0ad4abf1fa26d2bde77dea8921da25a48e
postgres/postgresql-11.15.tar.gz:
  size: 26509534
  object_id: 057118c1-9318-4d90-6f16-fda1977ec434
  sha: sha256:5f6ef2add1acb93d69012a55c3f276b91f4f0c91aa9a91243d9c5737ed5b5541
postgres/postgresql-13.6.tar.gz:
  size: 27878427
  object_id: 392a1eea-76a8-432b-4bfb-292608d11c9b
  sha: sha256:42dcde620b627d35bf51dfc2c1d0f7f25f44d3dbedd81cc459da2d2c9e859059
