boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.37.tar.gz:
  size: 2299767
  object_id: 8430a2b5-c852-413d-4286-3d1a44e8e61d
  sha: sha256:04e214c0c40a97b8a5c2b4ae88a3aa8a93e6f2e45c6b3534ddac351f26548577
mariadb/mariadb-10.6.3.tar.gz:
  size: 82053322
  object_id: 88d37d1d-1a4d-4a47-6387-f356aa2aaa42
  sha: sha256:5bc125606af5ec1fda80f594c1ddfacef8b305c158ecf8b1ca7a3f01cd0b18db
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.33.tar.gz:
  size: 56179381
  object_id: 83b9aa6b-de0f-4990-4b56-6ee9ead37f62
  sha: sha256:ad3b8d80d7b6e307cdf9eb061cbecccfe78bb5ecef24f2b17818d8e3ea2063ad
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.22.tar.gz:
  size: 24664093
  object_id: 615fbd06-3877-4433-6ebc-5d6da3f8cc34
  sha: sha256:f87eb4d0334d8736e61bc59383a802162a0897268b18e16138f6a2d7d218e705
postgres/postgresql-10.12.tar.gz:
  size: 24940708
  object_id: ac1c2ee7-6a96-4277-48e4-348cdd830c03
  sha: sha256:a1a32c2b91bc5e3cb46b56f44d6b6baf82cd27eff973d6c1785f4ab93e34d23b
postgres/postgresql-11.12.tar.gz:
  size: 26282000
  object_id: 668b7977-987f-47ba-49cb-8f57f8117905
  sha: sha256:fba997582e2e6ac0f6b5f400d12fbae53d2da0b9decdbe626ef3679689dacef6
postgres/postgresql-13.2.tar.gz:
  size: 27548921
  object_id: 39d39e69-b8f6-482e-4c20-3644319eefa4
  sha: sha256:3386a40736332aceb055c7c9012ecc665188536d874d967fcc5a33e7992f8080
