boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.40.tar.gz:
  size: 2359622
  object_id: 71c9fce6-53f5-4775-525c-fb5a75a3528a
  sha: sha256:ded42661cab30ada2e72ebff9e725e745b4b16ce831993635136f2ef86177724
mariadb/mariadb-10.6.8.tar.gz:
  size: 88794744
  object_id: 2c68687b-7280-435e-6e41-3ff01c2de2ec
  sha: sha256:57a9488559ccbdfb8506b781089a7a08d8e0e1b647cffb8f2706af06f69ed438
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.38.tar.gz:
  size: 56247722
  object_id: fc5eb46b-585b-455a-70c5-f174d518e490
  sha: sha256:22bf87eefa975b92b54d7c72fb5f3772c657cb0eb055bc6aea65d3a75f69a356
openssl/openssl-1.1.1o.tar.gz:
  size: 9856386
  object_id: 49453dd9-155f-49c7-4e90-c7fd6293c02f
  sha: sha256:9384a2b0570dd80358841464677115df785edb941c71211f75076d72fe6b438f
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.21.tar.gz:
  size: 25419930
  object_id: 9c4a67c1-1e81-4f98-40be-713a98681ee4
  sha: sha256:e2d2e9de7fa2b4ca73a619f19dc225eff60c53c0f093262e35a7a30ff0bfb97a
postgres/postgresql-11.17.tar.gz:
  size: 26671622
  object_id: 6bee55a3-261c-4209-4b32-9dc181942785
  sha: sha256:cabae4206160541797ea2547689eb64de9dd767a5a1ca1b721cee009fbdde752
postgres/postgresql-13.7.tar.gz:
  size: 28000563
  object_id: 4460a3ff-e506-4065-5295-3bd8625ebb3d
  sha: sha256:126b24fd5d11a3e84ec04630926321e26f1386dcebf0059c7d865988b03a4317
