boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.40.tar.gz:
  size: 2359622
  object_id: 71c9fce6-53f5-4775-525c-fb5a75a3528a
  sha: sha256:ded42661cab30ada2e72ebff9e725e745b4b16ce831993635136f2ef86177724
mariadb/mariadb-10.6.8.tar.gz:
  size: 88794744
  object_id: 2c68687b-7280-435e-6e41-3ff01c2de2ec
  sha: sha256:57a9488559ccbdfb8506b781089a7a08d8e0e1b647cffb8f2706af06f69ed438
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.37.tar.gz:
  size: 56248775
  object_id: bda6d410-4f86-42b3-600a-7705c210ee57
  sha: sha256:a99a9aa8635d2566dab764b2de56bed1730365d360e20bb27f56392ce54e18bd
openssl/openssl-1.1.1o.tar.gz:
  size: 9856386
  object_id: 49453dd9-155f-49c7-4e90-c7fd6293c02f
  sha: sha256:9384a2b0570dd80358841464677115df785edb941c71211f75076d72fe6b438f
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.21.tar.gz:
  size: 25419930
  object_id: 9c4a67c1-1e81-4f98-40be-713a98681ee4
  sha: sha256:e2d2e9de7fa2b4ca73a619f19dc225eff60c53c0f093262e35a7a30ff0bfb97a
postgres/postgresql-11.16.tar.gz:
  size: 26627640
  object_id: 65a985a2-2d89-42b0-4337-013e96a0f374
  sha: sha256:cf724fad7bd1820362558598360e9247deda61ccdf4bf542c4c7ad8fdad1b0c0
postgres/postgresql-13.8.tar.gz:
  size: 28046336
  object_id: 0f2a5efd-ef59-426f-7612-a6b76ba6787f
  sha: sha256:b0742c4e2a577afc9a3b31b19ee65e2b8369664676b119904a56028f0cefddbe
