boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.47.tar.gz:
  size: 2792969
  object_id: 9bd5dd3e-b4a0-4733-447a-ba56776d23d8
  sha: sha256:c08ae2388ef333e8403e670ad70c0a11f1eed021fd88308d7e02f596fcd9dc16
mariadb/mariadb-10.6.24.tar.gz:
  size: 107184510
  object_id: f4a2fe00-fe63-456f-5ac6-65d299fa350d
  sha: sha256:49e2badc674570c860e3cb7a2c016124aa6628c95f30133030411e5c89aa172f
mysql/mysql-5.7.44.tar.gz:
  size: 56570597
  object_id: 92e82aaa-6a33-40b7-5940-2366d90ad636
  sha: sha256:d03d8ff688862c40da3488451072a4b2178a86b53b4a7546ee5f864bb15cd919
mysql/mysql-8.0.44-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 61210260
  object_id: 5b3a98ae-ba7a-41f2-7415-1fef6d025fae
  sha: sha256:ef1197e8edbdd916a6e5f1dc4525c5a2a29d5cd7c86f19cd17383ecf354ef67c
ncurses/ncurses-6.6.tar.gz:
  size: 3791150
  object_id: 66926dd4-d034-4092-41d2-506b35dd7eba
  sha: sha256:355b4cbbed880b0381a04c46617b7656e362585d52e9cf84a67e2009b749ff11
postgres/postgresql-13.23.tar.gz:
  size: 28506793
  object_id: 9abf36c3-f575-40b8-6891-2f7c415b6b6b
  sha: sha256:f5eb642f659d59a9a65df08a1364fed8e83db5df116eff17a2f063a02854069b
postgres/postgresql-15.15.tar.gz:
  size: 30605101
  object_id: 3646fc78-1b26-4ddc-76ee-ae119e778460
  sha: sha256:c4502ab001cf4385d07f9f2bf40957cd8b81da323f72d6b5918307c8152575f0
