boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.40.tar.gz:
  size: 2359622
  object_id: 71c9fce6-53f5-4775-525c-fb5a75a3528a
  sha: sha256:ded42661cab30ada2e72ebff9e725e745b4b16ce831993635136f2ef86177724
mariadb/mariadb-10.6.11.tar.gz:
  size: 94742041
  object_id: 373d9167-4989-4d0b-511e-fa4eed645158
  sha: sha256:5784ba4c5d8793badba58348576824d9849ec152e9cbee47a1765161d840c94a
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.40.tar.gz:
  size: 56523688
  object_id: b9e7459c-91e7-433d-4e6f-9618d02fd214
  sha: sha256:b967898bf360cf21c43f372975ff56970100d560213806e7a0fe74b4930f4b9b
mysql/mysql-8.0.31-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 60148296
  object_id: 6029432e-38d0-4ff0-6af0-b55d25fbbff2
  sha: sha256:925d51cd2b05af536d035eb2f6ffe3acf42dd2c43993f91fc98d925d56a937de
ncurses/ncurses-6.4.tar.gz:
  size: 3612591
  object_id: 2e99f0f8-be87-480b-4e5a-9488e923e4d1
  sha: sha256:6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
openssl/openssl-1.1.1o.tar.gz:
  size: 9856386
  object_id: 49453dd9-155f-49c7-4e90-c7fd6293c02f
  sha: sha256:9384a2b0570dd80358841464677115df785edb941c71211f75076d72fe6b438f
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 9e0e0f74-07cf-4600-60a5-90a278783d5f
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-11.18.tar.gz:
  size: 26714356
  object_id: b333cdd3-f344-4159-5852-173cb2e6f01c
  sha: sha256:3c693225e26b3c40f40d7cbbc1409edb2e7db8072a9b3a7d4d3eb73c131c5a3b
postgres/postgresql-13.10.tar.gz:
  size: 28117237
  object_id: 17fbc832-4227-43e9-5f49-ad372d922b9b
  sha: sha256:a0a6b1b2e575fb15aa617fb77d3f2558ffd58a456e58d7d147539923d46d79cc
postgres/postgresql-15.1.tar.gz:
  size: 29778341
  object_id: 1d10fd47-0364-4e8f-7845-6bfcc52a95b2
  sha: sha256:ea2cf059a85882654b989acd07edc121833164a30340faee0d3615cf7058e66c
