boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.39.tar.gz:
  size: 2309964
  object_id: f3b818ce-0e2a-40ff-7fb6-edf0cfcb7b90
  sha: sha256:0781bd2536ef5279b1943471fdcdbd9961a2845e1d2c9ad849b9bd98ba1a9bd4
mariadb/mariadb-10.6.5.tar.gz:
  size: 85061860
  object_id: d0880acd-8e5c-4647-41e2-81eb1fdae3ed
  sha: sha256:e0be040428d9a42a8bb4bd221b567ff2522cd6fa8906386273da4f03c5c20a8f
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.36.tar.gz:
  size: 56238341
  object_id: 097a1be2-f209-43cd-5876-c58e7de93ff5
  sha: sha256:7a5c51170bc6fcd2bde91a3df9a01d62dc672184c4d5da49279a7ffd5863b774
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.20.tar.gz:
  size: 25307690
  object_id: d017c385-856a-4865-7cf9-1e93bced4fc4
  sha: sha256:403bdad47101f7c0a15824627dd0fa0ad4abf1fa26d2bde77dea8921da25a48e
postgres/postgresql-11.14.tar.gz:
  size: 26409946
  object_id: 38d4ac42-4d36-4549-6350-4b0d1971bb1f
  sha: sha256:2ef6895169a9152c6bd97d21d130d9b056a7ba07bfa8b6ce184f0c74bb6fbf58
postgres/postgresql-13.6.tar.gz:
  size: 27878427
  object_id: 392a1eea-76a8-432b-4bfb-292608d11c9b
  sha: sha256:42dcde620b627d35bf51dfc2c1d0f7f25f44d3dbedd81cc459da2d2c9e859059
