boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.44.tar.gz:
  size: 2552792
  object_id: 437af3f5-bb15-4e7a-7bce-84ae55c85425
  sha: sha256:86b9cb0aa3bcb7994faa88018292bc704cdbb708e785f7c74352ff6ea7d3175b
mariadb/mariadb-10.6.19.tar.gz:
  size: 99979223
  object_id: 8a70379f-e4a6-4f53-51f6-162c30912908
  sha: sha256:bcecb0ff7b79a41344736fa994710787c15516d51eb7715f278c3f0fcb7e8703
mysql/mysql-8.0.39-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 60892392
  object_id: a26e652c-d6ec-4963-6886-f671489e4944
  sha: sha256:ed3722dcd91607e118ed6cf51246f7d0882d982b33dab2935a2ec6c6e1271f2e
ncurses/ncurses-6.5.tar.gz:
  size: 3688489
  object_id: 44145765-7530-4a4b-45fd-932d16aa3aa4
  sha: sha256:136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6
postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: 00576d0f-f9a2-4210-7db0-f1d1687c3327
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
postgres/postgresql-13.16.tar.gz:
  size: 28320674
  object_id: 776b7076-2154-4977-5395-5a727c5d0b8d
  sha: sha256:33647543546202825bdf89bfb71523b5aea12b3b0153a689f694a08ed02aa204
postgres/postgresql-15.8.tar.gz:
  size: 30390113
  object_id: 20e268a3-8b28-4521-6b7b-262c3445e337
  sha: sha256:09fb1b27187962df046e8c0d9a1a2a56f80fd7f8cd4e7f881cac09b7fa3c60e1
