boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
mariadb/mariadb-10.2.26.tar.gz:
  size: 73037655
  object_id: 58884c84-f59f-4893-6898-37a3f5d265fa
  sha: sha256:152fe941c4f2a352b2b3a4db1ef64e70235fd9ff055af62ad7bda9f2b2191528
mysql/mysql-5.6.45.tar.gz:
  size: 32525559
  object_id: 74122cca-1eb0-48dc-5722-c11b1fe93bd5
  sha: sha256:404d798974dd89aca4a19e67194b534eddc7508489982175978966360607aabb
mysql/mysql-5.7.27.tar.gz:
  size: 54398696
  object_id: 31c2e0e9-50cc-4c5d-70b3-7cdc2da65811
  sha: sha256:f8b65872a358d6f5957de86715c0a3ef733b60451dad8d64a8fd1a92bf091bba
postgres/postgresql-9.4.23.tar.gz:
  size: 21943235
  object_id: 3cf98c54-a09e-4ddf-65b5-90a7fb36034f
  sha: sha256:82e29128463bfb1961c4119d9da893baaa437620a29bc53ce08bf735b5810ea4
postgres/postgresql-9.6.14.tar.gz:
  size: 24424663
  object_id: 4a40a5f0-c155-4f82-6f81-12bc934b0460
  sha: sha256:13017e2703b6ecc7c3bf88b9075d3d1240e57883b75e3f6ee6b9979ca817fc2c
postgres/postgresql-10.12.tar.gz:
  size: 24940708
  object_id: ac1c2ee7-6a96-4277-48e4-348cdd830c03
  sha: sha256:a1a32c2b91bc5e3cb46b56f44d6b6baf82cd27eff973d6c1785f4ab93e34d23b
postgres/postgresql-11.4.tar.gz:
  size: 25915738
  object_id: 9ceca675-79d2-4488-7653-920be0ef3d17
  sha: sha256:2043ab71f2a435a9e77b4419f804525a0b9ec1ef37d19c1c2e4013dc1cae01a7
