boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
mariadb/mariadb-10.6.3.tar.gz:
  size: 82053322
  object_id: 88d37d1d-1a4d-4a47-6387-f356aa2aaa42
  sha: sha256:5bc125606af5ec1fda80f594c1ddfacef8b305c158ecf8b1ca7a3f01cd0b18db
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.33.tar.gz:
  size: 56179381
  object_id: 83b9aa6b-de0f-4990-4b56-6ee9ead37f62
  sha: sha256:ad3b8d80d7b6e307cdf9eb061cbecccfe78bb5ecef24f2b17818d8e3ea2063ad
postgres/postgresql-9.4.23.tar.gz:
  size: 21943235
  object_id: 3cf98c54-a09e-4ddf-65b5-90a7fb36034f
  sha: sha256:82e29128463bfb1961c4119d9da893baaa437620a29bc53ce08bf735b5810ea4
postgres/postgresql-9.6.14.tar.gz:
  size: 24424663
  object_id: 4a40a5f0-c155-4f82-6f81-12bc934b0460
  sha: sha256:13017e2703b6ecc7c3bf88b9075d3d1240e57883b75e3f6ee6b9979ca817fc2c
postgres/postgresql-10.12.tar.gz:
  size: 24940708
  object_id: ac1c2ee7-6a96-4277-48e4-348cdd830c03
  sha: sha256:a1a32c2b91bc5e3cb46b56f44d6b6baf82cd27eff973d6c1785f4ab93e34d23b
postgres/postgresql-11.4.tar.gz:
  size: 25915738
  object_id: 9ceca675-79d2-4488-7653-920be0ef3d17
  sha: sha256:2043ab71f2a435a9e77b4419f804525a0b9ec1ef37d19c1c2e4013dc1cae01a7
postgres/postgresql-13.3.tar.gz:
  size: 27610951
  sha: sha256:0b54a8a68dbfaf5dcddd89eb3922740143df50fbea02fefda8de743d8af99516
