boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.42.tar.gz:
  size: 2397194
  object_id: 108c3b1c-687e-40dc-5768-6a353bafd4fa
  sha: sha256:c33b418e3b936ee3153de2c61cc638e7e4fe3156022a5c77d0711bcbb9d64f1f
mariadb/mariadb-10.6.12.tar.gz:
  size: 95085449
  object_id: 9707fde3-baa6-4ff5-5aea-9735e8b30bde
  sha: sha256:3ed2eb7429c2fae5423ca55c661742d107e35246f1ab0c107096f0c4b839463a
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.42.tar.gz:
  size: 56553748
  object_id: 288e955d-5702-4464-4d32-723a89935417
  sha: sha256:211cacb4b3e46dea59949092662be333ec677edb8bc41f4a6f2744e979ee19a2
mysql/mysql-8.0.33-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 60181648
  object_id: a2efd5cb-ae50-449c-6b10-b296700e69ac
  sha: sha256:ffd8384862a01d8c08d3c363bb98fb86fee1b0b229ebc99ee6658cc809892ddb
ncurses/ncurses-6.4.tar.gz:
  size: 3612591
  object_id: 2e99f0f8-be87-480b-4e5a-9488e923e4d1
  sha: sha256:6931283d9ac87c5073f30b6290c4c75f21632bb4fc3603ac8100812bed248159
openssl/openssl-1.1.1o.tar.gz:
  size: 9856386
  object_id: 49453dd9-155f-49c7-4e90-c7fd6293c02f
  sha: sha256:9384a2b0570dd80358841464677115df785edb941c71211f75076d72fe6b438f
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.23.tar.gz:
  size: 25493839
  object_id: 9e0e0f74-07cf-4600-60a5-90a278783d5f
  sha: sha256:39886b7fbf375fdd79e94b676d8346a62c3c190ccf00b3f763002c8fc8fb71f0
postgres/postgresql-11.19.tar.gz:
  size: 26735155
  object_id: 67fadba3-d4da-4e61-6bbd-9d1e3b424f4b
  sha: sha256:e1cb916e325170fcdde1a02de25d26792ffe3a08c3f2e1b9c7fc95ae2cabae7a
postgres/postgresql-13.11.tar.gz:
  size: 28159418
  object_id: 0b315e4c-58a0-456d-71ab-3351b48e6da9
  sha: sha256:b4f009f76cbc6c78e1e215eb78b2be4681240b861bdbb10cf36b0df7b2b75cac
postgres/postgresql-15.2.tar.gz:
  size: 29811750
  object_id: f7438a37-e7fd-43e0-6546-5c662e52b954
  sha: sha256:eccd208f3e7412ad7bc4c648ecc87e0aa514e02c24a48f71bf9e46910bf284ca
