boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.44.tar.gz:
  size: 2552792
  object_id: 437af3f5-bb15-4e7a-7bce-84ae55c85425
  sha: sha256:86b9cb0aa3bcb7994faa88018292bc704cdbb708e785f7c74352ff6ea7d3175b
mariadb/mariadb-10.6.17.tar.gz:
  size: 99067793
  object_id: c299f9bf-d7f2-4a13-56dc-75beb35461a3
  sha: sha256:fb41b0702059c046832d60138733acb73e4c0e5a1a0681061709d25591e4b086
mysql/mysql-5.7.44.tar.gz:
  size: 56570597
  object_id: 92e82aaa-6a33-40b7-5940-2366d90ad636
  sha: sha256:d03d8ff688862c40da3488451072a4b2178a86b53b4a7546ee5f864bb15cd919
mysql/mysql-8.0.38-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 60882036
  object_id: 11049533-3414-41bc-6376-30c773456e36
  sha: sha256:25b86cd71c0837d6c7d1fdd2165591388381e5541738b239e7b9772782a8f2b8
ncurses/ncurses-6.5.tar.gz:
  size: 3688489
  object_id: 44145765-7530-4a4b-45fd-932d16aa3aa4
  sha: sha256:136d91bc269a9a5785e5f9e980bc76ab57428f604ce3e5a5a90cebc767971cc6
openssl/openssl-1.1.1w.tar.gz:
  size: 9893384
  object_id: 8ebd05e7-9a12-4a1c-7a2d-5142e99bbcc0
  sha: sha256:cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8
postgres/postgresql-11.22.tar.gz:
  size: 26826810
  object_id: 00576d0f-f9a2-4210-7db0-f1d1687c3327
  sha: sha256:6445a4e1533c1e8bb616d4a3784bdc4c0226b541f6f0c8d996d9f27d581d49c3
postgres/postgresql-13.15.tar.gz:
  size: 28280167
  object_id: 4e80bf55-66fa-4bc7-7bd7-8f67e3802194
  sha: sha256:28e88226591247ea567ce26c4f5064ae5cc53cba94cb721ab8b6c6adea6218de
postgres/postgresql-15.7.tar.gz:
  size: 30332323
  object_id: f07d1a34-f7cf-4dc0-550e-ac41c03774e4
  sha: sha256:619541008e4c38560643a5dcfcfca49f39c7ba7f9b11896a88aaa2fd8eb71931
