boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 2bb21a57-51e9-471f-660a-edc788238fee
  sha: 5123209db194d66d69a9cfa5af8ff473d5941d97
libpcre2/pcre2-10.40.tar.gz:
  size: 2359622
  object_id: 71c9fce6-53f5-4775-525c-fb5a75a3528a
  sha: sha256:ded42661cab30ada2e72ebff9e725e745b4b16ce831993635136f2ef86177724
mariadb/mariadb-10.6.10.tar.gz:
  size: 96453293
  object_id: c5f9a09f-d82b-4d17-711c-19b72eda2614
  sha: sha256:6ad9fa86f0c85c8eeafad2643549d5ff5dd2872002964e754752de91863aa3b7
mysql/mysql-5.6.51.tar.gz:
  size: 32411131
  object_id: a8edb89b-908d-41d2-564a-d3fef5ad21cf
  sha: sha256:262ccaf2930fca1f33787505dd125a7a04844f40d3421289a51974b5935d9abc
mysql/mysql-5.7.39.tar.gz:
  size: 56517250
  object_id: 7068f2df-1452-4008-5ee3-c144d86ff2a9
  sha: sha256:111c3aca91897e453039db391a475265e020fd921cb97307c00084a88e4d6104
mysql/mysql-8.0.31-linux-glibc2.17-x86_64-minimal.tar.xz:
  size: 60148296
  sha: sha256:925d51cd2b05af536d035eb2f6ffe3acf42dd2c43993f91fc98d925d56a937de
ncurses/ncurses-6.3.tar.gz:
  size: 3583550
  sha: sha256:97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059
openssl/openssl-1.1.1o.tar.gz:
  size: 9856386
  object_id: 49453dd9-155f-49c7-4e90-c7fd6293c02f
  sha: sha256:9384a2b0570dd80358841464677115df785edb941c71211f75076d72fe6b438f
postgres/postgresql-9.4.26.tar.gz:
  size: 22001828
  object_id: e89adb5b-a26e-4dc2-5898-616fa1f5d2b6
  sha: sha256:b9206526343ba71f79aafb6b786a80d6e4777f64d3c8c0be6e5d47e1138a7d7e
postgres/postgresql-9.6.24.tar.gz:
  size: 24739272
  object_id: a1248b2f-d48d-48c2-4403-ae27e3cace4a
  sha: sha256:52947ecc119846eace5164399d173576c0d4a47ec116ae58a46a8fd0c576c7c3
postgres/postgresql-10.22.tar.gz:
  size: 25460734
  object_id: e65a2e31-839b-47b1-6d45-6e2caca39f5f
  sha: sha256:3ca98f49a31f595fd90664818eaa35a7a96d86123aedda8a023b2be8c96733f2
postgres/postgresql-11.17.tar.gz:
  size: 26671622
  object_id: 6bee55a3-261c-4209-4b32-9dc181942785
  sha: sha256:cabae4206160541797ea2547689eb64de9dd767a5a1ca1b721cee009fbdde752
postgres/postgresql-13.8.tar.gz:
  size: 28046336
  object_id: 0f2a5efd-ef59-426f-7612-a6b76ba6787f
  sha: sha256:b0742c4e2a577afc9a3b31b19ee65e2b8369664676b119904a56028f0cefddbe
