# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License‚Äù);
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: ((deployment-name))

releases:
- name: backup-and-restore-sdk
  version: ((backup-and-restore-sdk-release-version))
  url: ((backup-and-restore-sdk-release-url))
- name: minio
  version: latest
  url: https://bosh.io/d/github.com/minio/minio-boshrelease

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: backuper
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: concourse
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: ((s3-bucket-name))
          region: ((s3-region))
          aws_access_key_id: ((aws-access-key-id))
          aws_secret_access_key: ((aws-secret-access-key))
  azs: [z1]
- name: clone-backuper
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: concourse
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: ((s3-cloned-bucket-name))
          region: ((s3-cloned-bucket-region))
          aws_access_key_id: ((aws-access-key-id))
          aws_secret_access_key: ((aws-secret-access-key))
  azs: [z1]
- name: versioned-backuper-unversioned-bucket
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: concourse
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: ((s3-unversioned-bucket-name-for-versioned-backuper))
          region: ((s3-unversioned-bucket-region-for-versioned-backuper))
          aws_access_key_id: ((aws-access-key-id))
          aws_secret_access_key: ((aws-secret-access-key))
  azs: [z1]
- name: unversioned-custom-ca-cert-backuper
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: concourse
  jobs:
  - name: s3-versioned-blobstore-backup-restorer # temporarily using the versioned job until non-versioned is implemented
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          endpoint: https://10.245.1.7:9000
          name: systest-bucket
          region: us-east-1
          aws_access_key_id: ((minio-access-key))
          aws_secret_access_key: ((minio-secret-key))
  azs: [z1]
- name: minio
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: xenial
  networks:
  - name: concourse
    static_ips: [10.245.1.7]
  jobs:
  - name: minio-server
    release: minio
    properties:
      credential:
        accesskey: ((minio-access-key))
        secretkey: ((minio-secret-key))
      port: 9000
- name: s3-unversioned-backuper
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: fifty
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: concourse
  jobs:
  - name: s3-unversioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        my_bucket:
          name: ((s3-unversioned-bucket-name))
          region: ((s3-unversioned-bucket-region))
          aws_access_key_id: ((aws-access-key-id))
          aws_secret_access_key: ((aws-secret-access-key))
          backup:
            name: ((s3-unversioned-backup-bucket-name))
            region: ((s3-unversioned-backup-bucket-region))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000
  update_watch_time: 30000
