# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License‚Äù);
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: "((deployment-name))"

releases:
- name: backup-and-restore-sdk
  version: latest
- name: "minio"
  version: "2019-02-06T21-16-36Z"
  url: "https://bosh.io/d/github.com/minio/minio-boshrelease?v=2019-02-06T21-16-36Z"
  sha1: "19951d2d53d5057d6472427d6126386032b782c9"
- name: os-conf
  version: latest
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release
- name: bpm
  version: latest
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

variables:
- name: minio_ca
  type: certificate
  options:
    is_ca: true
    common_name: ((minio-host))
    alternative_names:
    - ((minio-host))

instance_groups:
- name: backuper
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: "((s3-bucket-name))"
          region: "((s3-region))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
  azs: [z1]
- name: backuper-bpm
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: "((s3-bucket-name))"
          region: "((s3-region))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
      bpm:
        enabled: true
  - name: bpm
    release: bpm
  azs: [z1]
- name: clone-backuper
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: "((s3-cloned-bucket-name))"
          region: "((s3-cloned-bucket-region))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
  azs: [z1]
- name: versioned-backuper-unversioned-bucket
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: s3-versioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          name: "((s3-unversioned-bucket-name-for-versioned-backuper))"
          region: "((s3-unversioned-bucket-region-for-versioned-backuper))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
  azs: [z1]
- name: unversioned-custom-ca-cert-backuper
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: ca_certs
    release: os-conf
    properties:
      certs: "((minio_ca.certificate))"
  - name: s3-versioned-blobstore-backup-restorer # temporarily using the versioned job until non-versioned is implemented
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        bucket_identifier:
          endpoint: https://((minio-host)):((minio-port))
          name: systest-bucket
          region: us-east-1
          aws_access_key_id: "((minio-access-key))"
          aws_secret_access_key: "((minio-secret-key))"
  azs: [z1]
- name: minio
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  networks:
  - name: default
    static_ips: [((minio-host))]
  jobs:
  - name: minio-server
    release: minio
    properties:
      ca_cert: "((minio_ca.ca))"
      server_cert: "((minio_ca.certificate))"
      server_key: "((minio_ca.private_key))"
      credential:
        accesskey: "((minio-access-key))"
        secretkey: "((minio-secret-key))"
      port: 9000
- name: s3-unversioned-backuper
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: s3-unversioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        my_bucket:
          name: "((s3-unversioned-bucket-name))"
          region: "((s3-unversioned-bucket-region))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
          backup:
            name: "((s3-unversioned-backup-bucket-name))"
            region: "((s3-unversioned-backup-bucket-region))"
- name: s3-unversioned-backuper-same-bucket
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
    - name: default
  jobs:
    - name: s3-unversioned-blobstore-backup-restorer
      release: backup-and-restore-sdk
      properties:
        enabled: true
        buckets:
          bucket1:
            name: "((s3-unversioned-bucket-name))"
            region: "((s3-unversioned-bucket-region))"
            aws_access_key_id: "((aws-access-key-id))"
            aws_secret_access_key: "((aws-secret-access-key))"
            backup:
              name: "((s3-unversioned-backup-bucket-name))"
              region: "((s3-unversioned-backup-bucket-region))"
          bucket2:
            name: "((s3-unversioned-bucket-name))"
            region: "((s3-unversioned-bucket-region))"
            aws_access_key_id: "((aws-access-key-id))"
            aws_secret_access_key: "((aws-secret-access-key))"
            backup:
              name: "((s3-unversioned-backup-bucket-name))"
              region: "((s3-unversioned-backup-bucket-region))"
- name: s3-unversioned-backuper-large-number-of-files
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: s3-unversioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      buckets:
        my_bucket:
          name: "((s3-unversioned-large-number-of-files-bucket-name))"
          region: "((s3-unversioned-large-number-of-files-bucket-region))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
          backup:
            name: "((s3-unversioned-large-number-of-files-backup-bucket-name))"
            region: "((s3-unversioned-large-number-of-files-backup-bucket-region))"
- name: s3-unversioned-backuper-clone
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
    - name: default
  jobs:
    - name: s3-unversioned-blobstore-backup-restorer
      release: backup-and-restore-sdk
      properties:
        enabled: true
        buckets:
          my_bucket:
            name: "((s3-unversioned-clone-bucket-name))"
            region: "((s3-unversioned-clone-bucket-region))"
            aws_access_key_id: "((aws-access-key-id))"
            aws_secret_access_key: "((aws-secret-access-key))"
            backup:
              name: "((s3-unversioned-backup-bucket-name))"
              region: "((s3-unversioned-backup-bucket-region))"
- name: s3-unversioned-backuper-bpm
  azs: [z1]
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  update:
    serial: true
  networks:
  - name: default
  jobs:
  - name: bpm
    release: bpm
  - name: s3-unversioned-blobstore-backup-restorer
    release: backup-and-restore-sdk
    properties:
      enabled: true
      bpm:
        enabled: true
      buckets:
        my_bucket:
          name: "((s3-unversioned-bpm-bucket-name))"
          region: "((s3-unversioned-bpm-bucket-region))"
          aws_access_key_id: "((aws-access-key-id))"
          aws_secret_access_key: "((aws-secret-access-key))"
          backup:
            name: "((s3-unversioned-bpm-backup-bucket-name))"
            region: "((s3-unversioned-bpm-backup-bucket-region))"
update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000
  update_watch_time: 30000
